import numpy as np
print("Loading features generated by Quantum_hack...")

X = np.load("data/X.npy")
y = np.load("data/y.npy")

print("Features loaded successfully!")
print("X shape:", X.shape)
print("y shape:", y.shape)


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("All libraries imported successfully!")


from sklearn.model_selection import train_test_split

good_df = features_df[features_df["label"] == 0].sample(
    n=100,
    random_state=42
)

defective_df = features_df[features_df["label"] == 1].sample(
    n=100,
    random_state=42
)

# Combine
dataset_200 = pd.concat(
    [good_df, defective_df],
    ignore_index=True
)

# Separate features and labels
X = dataset_200.drop(
    columns=["image_id", "label"]
)

y = dataset_200["label"]

# 80/20 split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Total images:", len(dataset_200))

print("\nTraining:")
print("Images:", len(X_train))
print(y_train.value_counts())

print("\nTesting:")
print("Images:", len(X_test))
print(y_test.value_counts())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Learn scaling ONLY from training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the SAME scaling to test data
X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed!")

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

from sklearn.svm import SVC

svm_model = SVC(
    kernel="rbf",
    C=1.0,
    probability=True
)

svm_model.fit(X_train_scaled, y_train)

print("SVM training completed!")

y_pred = svm_model.predict(X_test_scaled)

print("Prediction completed!")

print("\nActual labels:")
print(y_test.values)

print("\nPredicted labels:")
print(y_pred)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    pos_label=1,
    zero_division=0
)

cm = confusion_matrix(y_test, y_pred)


print("==========================================")
print("       QUANTUMINSPEC - SVM RESULTS")
print("==========================================")

print(f"Accuracy  : {accuracy:.4f}  ({accuracy*100:.2f}%)")
print(f"Precision : {precision:.4f}  ({precision*100:.2f}%)")
print(f"Recall    : {recall:.4f}  ({recall*100:.2f}%)")
print(f"F1 Score  : {f1:.4f}  ({f1*100:.2f}%)")

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=["GOOD", "DEFECTIVE"],
        zero_division=0
    )
)


import os
import joblib

# Create models folder
os.makedirs("models", exist_ok=True)


joblib.dump(
    svm_model,
    "models/svm_model.pkl"
)


joblib.dump(
    scaler,
    "models/svm_scaler.pkl"
)

svm_metrics = {
    "accuracy": accuracy,
    "precision": precision,
    "recall": recall,
    "f1": f1,
    "confusion_matrix": cm
}

joblib.dump(
    svm_metrics,
    "models/svm_metrics.pkl"
)

print("==========================================")
print("       SVM FILES SAVED SUCCESSFULLY")
print("==========================================")

print("✓ models/svm_model.pkl")
print("✓ models/svm_scaler.pkl")
print("✓ models/svm_metrics.pkl")